### ISSUE TITLE
Feedback on [GUIDE] Custom Aragon Organization Deployment using the CLI

### ISSUE THREAD

**Issue by chrishobcroft** [aragon/forum#2]
This issue captures feedback on [this document](https://forum.aragon.org/t/guide-custom-aragon-organization-deployment-using-the-cli/507/1) by @lkngtn:

### Proposed Improvements

1. **Help users see their DAO in a browser from the start** Under "Creating a blank organization". Maybe help users to find their DAO at rinkeby.aragon.org or mainnet.aragon.org. Something like:

> You can access the web-based UI by visiting http://rinkeby.aragon.org/#/[dao-address] or http://mainnet.aragon.org/#/[dao-address]

2. The `dao acl` commands to assign `MINT_ROLE`, `CREATE_VOTES_ROLE`, `CREATE_PAYMENTS_ROLE` all seem to execute successfully, BUT throw a cryptic error:

```
✖ Cannot read property 'description' of undefined
```

What is going wrong here? Any ideas?

### Typos

> We will create **_on_** voting app instance, but the process can be repeated as many times as required.

Should read **_one_**

> Since we already have a token and token manager deployed all **_way_** have to do is install the app

Should read **_we_**

> or configure CLI sign transactions using a private key

Should read "...configure CLI **_to_** sign..."

> Aragon uses tokens to represent groups, token balances can be capped to a certain amount per account made non-transferrable

should read:

- Aragon uses tokens to represent groups. Token balances can be capped to a certain amount per account **_and_** made non-transferrable

> So if we want a voting app **_instances_** with a support requirement of...

Should read **_instance_**

**Comment by lkngtn** [comment]
This guide was migrated to hack.aragon.org. I've submitted a PR there to address these suggestions. Thanks again for the feedback!
